name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ok-nick/setup-aftman@v0.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: List installed aftman tools
      run: aftman list

    - name: Generate Roblox standards
      run: selene generate-roblox-std

    - name: Run Selene
      run: selene --allow-warnings ./src

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ok-nick/setup-aftman@v0.4.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}


    - name: List installed aftman tools
      run: aftman list

    - name: Build plugin
      run: rojo build default.project.json -o roblox-gatherer-sdk.rbxlx
