name: Create Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

- name: Running release-it using GitHub Action
    uses: juancarlosjr97/release-it-containerized:0.2.0
    with:
        git_email: ${{ vars.GIT_EMAIL }}
        git_username: ${{ vars.GIT_USERNAME }}
        github_token: ${{ secrets.GITHUB_TOKEN }}  