name: wally-publish

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Wally publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List installed aftman tools
        run: aftman list

      - name: Publish to Wally
        env:
          WALLY_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
        run: |
          mkdir =p ~/.wally
          printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
          wally publish
