name: release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List installed aftman tools
        run: aftman list

      - name: Build Place
        run: rojo build -o GathererSDK.rbxm

      - uses: actions/upload-artifact@v4
        with:
          name: rbxm-file
          path: GathererSDK.rbxm

  release:
    name: Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Get next version"
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - uses: rickstaa/action-create-tag@v1
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        with:
          tag: "${{ steps.semvers.outputs.minor }}"
      - uses: rickstaa/action-create-tag@v1
        if: contains(github.event.pull_request.labels.*.name, 'major')
        with:
          tag: "${{ steps.semvers.outputs.major }}"
      - uses: rickstaa/action-create-tag@v1
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        with:
          tag: "${{ steps.semvers.outputs.patch }}"

      - uses: actions/download-artifact@v4
        with:
          name: rbxm-file

      - name: "Get Current tag"
        id: currenttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update wally.toml
        run: |
          sed -i 's/version = ".*"/version = "${{ steps.currenttag.outputs.tag }}"/' wally.toml
        shell: bash

      - name: Commit updated wally.toml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wally.toml
          git commit -m "Update wally.toml version to ${{ steps.currenttag.outputs.tag }}"
          git push

      - name: Create Github release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ steps.currenttag.outputs.tag }} -t ${{ steps.currenttag.outputs.tag }} --generate-notes --latest GathererSDK.rbxm

      - name: Publish to Wally
        env:
          WALLY_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
        run: |
          mkdir =p ~/.wally
          printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
          wally publish
