name: release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List installed aftman tools
        run: aftman list

      - name: Build Place
        run: rojo build -o roblox-gatherer-sdk.rbxl

      - name: Publish SDK to Roblox
        shell: bash
        env:
          REMODEL_AUTH: ${{ secrets.ROBLOX_API_KEY }}
        run: |
          remodel run publish.luau

      - uses: actions/upload-artifact@v4
        with:
          name: rbxm-file
          path: GathererSDK.rbxm

  release:
    name: Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Get next version"
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - uses: rickstaa/action-create-tag@v1
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        with:
          tag: "${{ steps.semvers.outputs.minor }}"
      - uses: rickstaa/action-create-tag@v1
        if: contains(github.event.pull_request.labels.*.name, 'major')
        with:
          tag: "${{ steps.semvers.outputs.major }}"
      - uses: rickstaa/action-create-tag@v1
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        with:
          tag: "${{ steps.semvers.outputs.patch }}"

      - uses: actions/download-artifact@v4
        with:
          name: rbxm-file

      - name: "Get Current tag"
        id: currenttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Github release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ steps.currenttag.outputs.tag }} -t ${{ steps.currenttag.outputs.tag }} --generate-notes --latest GathererSDK.rbxm
